// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshvGmgcB3X8JJpG7v1jvJuyOPLv7R3jU',
    appId: '1:597433345372:web:7d8ee437e28a7e9ffc0d99',
    messagingSenderId: '597433345372',
    projectId: 'parlouraccount-a38a7',
    authDomain: 'parlouraccount-a38a7.firebaseapp.com',
    storageBucket: 'parlouraccount-a38a7.firebasestorage.app',
    measurementId: 'G-1ZXCRXEBL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA00-_pV1ShJHhzKt4HcWzNBxJIye_uAGY',
    appId: '1:597433345372:android:2f9e226bb95dea20fc0d99',
    messagingSenderId: '597433345372',
    projectId: 'parlouraccount-a38a7',
    storageBucket: 'parlouraccount-a38a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlI32QxgMlJDu6kravu7qBk9IbrU_pf5M',
    appId: '1:597433345372:ios:4614340dad81ab70fc0d99',
    messagingSenderId: '597433345372',
    projectId: 'parlouraccount-a38a7',
    storageBucket: 'parlouraccount-a38a7.firebasestorage.app',
    iosBundleId: 'com.example.parlourAccount',
  );
}
